### PR TITLE
OpenGL renderer and backend-agnostic graphics subcrate

### LINKED ISSUE #70: Winit Error when running Example on Ubuntu 19.04
Getting the following error when trying to run `cargo run --example tour` on my Ubuntu 19.04 lappy.

```
[2019-11-25T23:31:50Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
```

### LINKED ISSUE #72: Error when running examples: "extension NV-GLX missing on display"
I get these errors when I try to run the examples:

### todos

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/todos`
Xlib:  extension "NV-GLX" missing on display ":0.0".
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: core::option::Option<T>::unwrap
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/macros.rs:41
  16: wgpu_request_adapter
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.0/src/instance.rs:474
  17: wgpu::Adapter::request
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  18: iced_wgpu::renderer::Renderer::new
             at wgpu/src/renderer.rs:51
  19: <iced_wgpu::renderer::Renderer as iced_native::renderer::windowed::Windowed>::new
             at wgpu/src/renderer.rs:417
  20: iced_winit::application::Application::run
             at ./winit/src/application.rs:115
  21: iced::application::Application::run
             at ./src/application.rs:140
  22: todos::main
             at examples/todos.rs:9
  23: std::rt::lang_start::{{closure}}
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libstd/rt.rs:61
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  27: std::panicking::try
             at src/libstd/panicking.rs:265
  28: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  29: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  30: std::rt::lang_start
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libstd/rt.rs:61
  31: main
  32: __libc_start_main
  33: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### tour

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/tour`
Xlib:  extension "NV-GLX" missing on display ":0.0".
[2019-11-26T06:18:57Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94410943735344)
    
[2019-11-26T06:18:57Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94410943735344)
    
[2019-11-26T06:18:57Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94410943735344)
    
[2019-11-26T06:18:57Z ERROR gfx_backend_vulkan] 
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94410943735344)
    
[2019-11-26T06:18:57Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: core::option::Option<T>::unwrap
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libcore/macros.rs:41
  16: wgpu_request_adapter
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.0/src/instance.rs:474
  17: wgpu::Adapter::request
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  18: iced_wgpu::renderer::Renderer::new
             at wgpu/src/renderer.rs:51
  19: <iced_wgpu::renderer::Renderer as iced_native::renderer::windowed::Windowed>::new
             at wgpu/src/renderer.rs:417
  20: iced_winit::application::Application::run
             at ./winit/src/application.rs:115
  21: iced::application::Application::run
             at ./src/application.rs:140
  22: iced::sandbox::Sandbox::run
             at ./src/sandbox.rs:128
  23: tour::main
             at examples/tour.rs:10
  24: std::rt::lang_start::{{closure}}
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libstd/rt.rs:61
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  28: std::panicking::try
             at src/libstd/panicking.rs:265
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  31: std::rt::lang_start
             at /rustc/1423bec54cf2db283b614e527cfd602b481485d1/src/libstd/rt.rs:61
  32: main
  33: __libc_start_main
  34: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### LINKED ISSUE #96: No Text, no Buttons
I'm running on Windows 10 (1909), building with Visual Studio Code and the Rust version x86_64-pc-windows-msvc 1.39 and the counter example compiles fine with no issues. When the window comes up the title is there and the window works as I would expect. other then there is no text or button in the window?

Obviously I'm doing something wrong, any ideas?

Thanks,

Ashley

### LINKED ISSUE #98: Another run example error: `cargo run --example tour`
I'm trying to run the example on my Windows 10, but I come across this: 

```powershell
iced> $Env:RUST_BACKTRACE="full"
iced> cargo run --example tour  
    Finished dev [unoptimized + debuginfo] target(s) in 0.63s
     Running `target\debug\examples\tour.exe`
[2019-12-01T05:21:46Z INFO  winit::platform_impl::platform::window] Guessed window DPI factor: 1
error: process didn't exit successfully: `target\debug\examples\tour.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

I tried to backtrace the log, But it seems to only print a line of log about DPI factor. How could I log more to locate this issue?

### LINKED ISSUE #148: Crashes with assertion failed
Unfortunately, whenever I try to run any example, a window pops up then immediately closes with the following assertion failure

```
thread 'main' panicked at 'assertion failed: suf.supports_queue_family(&adapter.raw.queue_families[0])', /home/{USER}/.cargo/registry/src/{...}/wgpu-native-0.4.2/src/device.rs:2065:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I'm assuming this has to do with the environment I'm running this in? I'm using Linux Manjaro with a GTX 1080 and a Coffee Lake CPU.

### LINKED ISSUE #182: Examples fail on Macs without Metal support
Neat project! I just tried taking things for a spin, but it's failed:

```
$ RUST_BACKTRACE=full cargo run --package progress_bar
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/progress_bar`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:        0x104ecd735 - backtrace::backtrace::libunwind::trace::hb16ec6045891ce5a
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x104ecd735 - backtrace::backtrace::trace_unsynchronized::hcacbd0efdffd74c6
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x104ecd735 - std::sys_common::backtrace::_print_fmt::h39e22de9d6757d12
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x104ecd735 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415ddd0ba88caaaf
                               at src/libstd/sys_common/backtrace.rs:61
   4:        0x104eebf20 - core::fmt::write::h3335552e2df81c1d
                               at src/libcore/fmt/mod.rs:1028
   5:        0x104ecbb4b - std::io::Write::write_fmt::he6837371b9a45188
                               at src/libstd/io/mod.rs:1412
   6:        0x104ecf4c3 - std::sys_common::backtrace::_print::h89459d14ba97f5fa
                               at src/libstd/sys_common/backtrace.rs:65
   7:        0x104ecf4c3 - std::sys_common::backtrace::print::ha4c6688e811b8829
                               at src/libstd/sys_common/backtrace.rs:50
   8:        0x104ecf4c3 - std::panicking::default_hook::{{closure}}::h708e66cfeb0483ba
                               at src/libstd/panicking.rs:188
   9:        0x104ecf1ca - std::panicking::default_hook::h39ea8ddf674c04ec
                               at src/libstd/panicking.rs:205
  10:        0x104ecfc0b - std::panicking::rust_panic_with_hook::h9db77b22c2255a16
                               at src/libstd/panicking.rs:464
  11:        0x104ecf769 - std::panicking::continue_panic_fmt::h2dfa3a5b90265361
                               at src/libstd/panicking.rs:373
  12:        0x104ecf669 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:        0x104ee811c - core::panicking::panic_fmt::hec1ee47b7e17dca5
                               at src/libcore/panicking.rs:139
  14:        0x104ee8074 - core::panicking::panic::h30fe7b508c26b15d
                               at src/libcore/panicking.rs:70
  15:        0x1047dc1e0 - core::option::Option<T>::unwrap::hbec2fdf7224360a8
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/macros.rs:41
  16:        0x10492a144 - wgpu_request_adapter
                               at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  17:        0x1046b563d - wgpu::Adapter::request::ha66b32bd73380b41
                               at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  18:        0x1045f5910 - iced_wgpu::renderer::Renderer::new::h0682673c8b9bd9dc
                               at wgpu/src/renderer.rs:57
  19:        0x1045f73f4 - <iced_wgpu::renderer::Renderer as iced_native::window::renderer::Renderer>::new::h83bcc0cb7e69d4e0
                               at wgpu/src/renderer.rs:463
  20:        0x1044cd175 - iced_winit::application::Application::run::h9acff3abb7370115
                               at /Users/me/Documents/Code/rust/other/iced/winit/src/application.rs:169
  21:        0x1044a570f - iced::application::Application::run::h5d35e322149e3428
                               at /Users/me/Documents/Code/rust/other/iced/src/application.rs:177
  22:        0x1044a58c0 - iced::sandbox::Sandbox::run::h86da6c61095980ec
                               at /Users/me/Documents/Code/rust/other/iced/src/sandbox.rs:128
  23:        0x1044cddaa - progress_bar::main::hb68c8566db5e82d4
                               at examples/progress_bar/src/main.rs:4
  24:        0x1044a8672 - std::rt::lang_start::{{closure}}::h7a47d33c58d14eee
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25:        0x104ecf5e8 - std::rt::lang_start_internal::{{closure}}::hccd7db6d8a0ebab5
                               at src/libstd/rt.rs:48
  26:        0x104ecf5e8 - std::panicking::try::do_call::hd5a3af8d00c06681
                               at src/libstd/panicking.rs:287
  27:        0x104ed1bdf - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  28:        0x104ed005e - std::panicking::try::h7a0bd4c078131d2f
                               at src/libstd/panicking.rs:265
  29:        0x104ed005e - std::panic::catch_unwind::h75c3fbe62776ab10
                               at src/libstd/panic.rs:396
  30:        0x104ed005e - std::rt::lang_start_internal::haa52aabac43378ff
                               at src/libstd/rt.rs:47
  31:        0x1044a8652 - std::rt::lang_start::h20470961c581b479
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  32:        0x1044ce072 - progress_bar::Message::SliderChanged::hefc33626c8183d38
```

I can try on macOS 10.14 if you need output from a Metal target as well.

### LINKED ISSUE #194: problem while running compiled app
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/counter`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### LINKED ISSUE #212: Panic running examples on Ubuntu 18.04
Error message.
```shell
charles@charles-TE:~/rust/iced/examples/progress_bar (master)
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `/home/charles/rust/iced/target/debug/progress_bar`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
``` 
```shell
charles@charles-TE:~/rust/iced/examples/progress_bar (master)
$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Am i attempting to run this incorrectly ?
I have done a clean build. are there any libraries I need to support this ? 
or some command line arguments to target a specific renderer ?

Works fine on my windows target, just my ubuntu target that is failing.

### LINKED ISSUE #257: "cargo run --package tour" opens a window, but it’s invisible
It took me a while to get everything compiling and running under NixOS. I can now compile and run the `tour` package, but I can’t see or interact with the window that (supposedly) opens. You can see in the attached screenshots that my desktop looks the same whether my terminal or the iced window is focused.

I’m using i3 on nixos-unstable. My graphics card is an onboard Intel device.
iced_focused
terminal_focused

### LINKED ISSUE #284: Error running example
```
$ RUST_BACKTRACE=full cargo run --package counter
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/counter`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
stack backtrace:
   0:     0x560854118704 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x560854118704 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x560854118704 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x560854118704 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x560854138bcc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x560854115917 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x56085411a905 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56085411a905 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56085411a905 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x56085411a5f1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x56085411af6a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x56085411ab50 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x560854136a61 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x5608541369ad - core::panicking::panic::hcdc9f0ba8d71d265
                               at src/libcore/panicking.rs:52
  14:     0x56085396ad37 - core::option::Option<T>::unwrap::hce042dfbc1ff19aa
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  15:     0x560853aaa266 - wgpu_request_adapter
                               at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16:     0x5608538fe74e - wgpu::Adapter::request::h6dc55b08ffb36bde
                               at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17:     0x560853833f01 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::hd0c4ebe110ed2945
                               at wgpu/src/window/backend.rs:21
  18:     0x56085374ce71 - iced_winit::application::Application::run::hef13b9c0f72c1191
                               at /home/justin/dev/iced/winit/src/application.rs:180
  19:     0x56085379e647 - iced::application::Application::run::h1ebca9439a54ea39
                               at /home/justin/dev/iced/src/application.rs:201
  20:     0x56085379e811 - iced::sandbox::Sandbox::run::hd5f9e38d01e4f439
                               at /home/justin/dev/iced/src/sandbox.rs:139
  21:     0x5608537d48c8 - counter::main::h2f03e7b2adf2d880
                               at examples/counter/src/main.rs:4
  22:     0x5608537cc440 - std::rt::lang_start::{{closure}}::h1c8f60ca6472e181
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  23:     0x56085411aa33 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  24:     0x56085411aa33 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  25:     0x56085411ed77 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:     0x56085411b4d0 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  27:     0x56085411b4d0 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  28:     0x56085411b4d0 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  29:     0x5608537cc419 - std::rt::lang_start::h2572600627a9280f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  30:     0x5608537d4d9a - main
  31:     0x7f02dea69023 - __libc_start_main
  32:     0x5608537411ae - _start
  33:                0x0 - <unknown>
```

I'm on Arch Linux:

```
$ uname -srm
Linux 5.5.13-arch2-1 x86_64
```

### LINKED ISSUE #342: Canvas examples on MacOS don't work
0.1.1 seems to have broken the Canvas widget on Mac OS. When trying to run the clock, solar_system, bezier_tool examples on MacOS 10.14.6 get a blank, white, screen where I believe the Canvas is supposed to be. Running game_of_life presents a gray screen, and all the surrounding menu components but does not show any of the white "cell" pieces.

Manually switching to the 0.1 branch and testing the ones that exist there seems to work fine.

### LINKED ISSUE #349: Crash when using more than one custom widgets that use Canvas features for rendering
I am trying to create custom widgets that use the Canvas rendering features of iced. However, it is crashing when I have two or more widgets that render using this feature. It only crashes on debug mode; running with `--release` shows it rendering correctly.

I attached an example that causes this crash.
[iced_stroke_crash.zip](https://github.com/hecrj/iced/files/4645484/iced_stroke_crash.zip)

The output of `env RUST_BACKTRACE=full cargo run`:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `64`,
 right: `0`: Misaligned dynamic buffer offset: 64 does not align with 256', /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:251:13
stack backtrace:
   0:     0x55b46edb94c4 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55b46edb94c4 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55b46edb94c4 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55b46edb94c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b46eddc00c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55b46edb6663 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x55b46edbbd05 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b46edbbd05 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b46edbbd05 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x55b46edbba52 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x55b46edbc362 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x55b46edbbf4b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55b46edbbebb - std::panicking::begin_panic_fmt::h7c14cf40a8be97ee
                               at src/libstd/panicking.rs:332
  13:     0x55b46e7f24d4 - wgpu_native::command::render::render_pass_set_bind_group::h9df561ef5a26152d
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:251
  14:     0x55b46e7f2a52 - wgpu_render_pass_set_bind_group
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:297
  15:     0x55b46e5e9c2e - wgpu::RenderPass::set_bind_group::h01a2de7a6c65fb1a
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1157
  16:     0x55b46e5964da - iced_wgpu::triangle::Pipeline::draw::h219b1ee83175a9d0
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/triangle.rs:327
  17:     0x55b46e55bff5 - iced_wgpu::renderer::Renderer::flush::hd20eeb865cd78511
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/renderer.rs:358
  18:     0x55b46e4cdb28 - iced_wgpu::renderer::Renderer::draw::hee34b70b05c12c73
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/renderer.rs:114
  19:     0x55b46e49a485 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::draw::h8414819477e8cf4e
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/window/backend.rs:97
  20:     0x55b46e49e756 - iced_winit::application::Application::run::{{closure}}::h665596509eee0f77
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:331
  21:     0x55b46e4fc0b3 - winit::platform_impl::platform::sticky_exit_callback::h015bde6614d2d436
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  22:     0x55b46e4b6887 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h77b2bd376478e000
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:312
  23:     0x55b46e4b791b - winit::platform_impl::platform::x11::EventLoop<T>::run::h1c6d93965899b975
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390
  24:     0x55b46e4fbe4c - winit::platform_impl::platform::EventLoop<T>::run::h7560f22bb7937768
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645
  25:     0x55b46e4faea4 - winit::event_loop::EventLoop<T>::run::hb18bd6bf7e9201a2
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  26:     0x55b46e4bad04 - iced_winit::application::Application::run::h284668e780a9be6b
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:214
  27:     0x55b46e46f0e7 - iced::application::Application::run::h99fa56672e3e9edf
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/application.rs:201
  28:     0x55b46e46f281 - iced::sandbox::Sandbox::run::h4b850fa20e1b778a
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/sandbox.rs:139
  29:     0x55b46e506098 - iced_stroke_crash::main::h75d879cb5dc3a483
                               at src/main.rs:110
  30:     0x55b46e4fd2db - std::rt::lang_start::{{closure}}::h5d116171458e5b05
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  31:     0x55b46edbbe23 - std::rt::lang_start_internal::{{closure}}::h9a4aa16acf1cdc99
                               at src/libstd/rt.rs:52
  32:     0x55b46edbbe23 - std::panicking::try::do_call::h0b6fc9f6090c1e2b
                               at src/libstd/panicking.rs:303
  33:     0x55b46edc01b7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x55b46edbc94c - std::panicking::try::h9eaeeaa81242ec77
                               at src/libstd/panicking.rs:281
  35:     0x55b46edbc94c - std::panic::catch_unwind::h07d504c1b691e8fb
                               at src/libstd/panic.rs:394
  36:     0x55b46edbc94c - std::rt::lang_start_internal::hcea4e704875ab132
                               at src/libstd/rt.rs:51
  37:     0x55b46e4fd2b7 - std::rt::lang_start::h3930cc3841bbba4e
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  38:     0x55b46e50640a - main
  39:     0x7fa37919d023 - __libc_start_main
  40:     0x55b46e4691ae - _start
  41:                0x0 - <unknown>
```

I am running Manjaro Linux with kernel version 5.5.19-1-MANJARO and the Budgie desktop environment. I am using an AMD RX 570 graphics card.

My graphics card info from `lspci -v`
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
        Subsystem: XFX Pine Group Inc. Radeon RX 570
        Flags: bus master, fast devsel, latency 0, IRQ 35
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=2M]
        I/O ports at e000 [size=256]
        Memory at dfe00000 (32-bit, non-prefetchable) [size=256K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
        Subsystem: XFX Pine Group Inc. Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
        Flags: bus master, fast devsel, latency 0, IRQ 34
        Memory at dfe60000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
```

### LINKED ISSUE #350: White screen on tour example
When I run the tour example I'm only getting a white screen.  Every other example I've tried has worked.

I managed to get it working by removing the "image" feature requirement in Cargo.toml and commenting out the actual image loading in the ferris() function and replacing it with a Text widget instead.  Even with the image loading commented out, it's still white screens, only removing the feature requirement lets it work.

The pokedex example does work even though it includes the same "image" feature.  I'm stumped without diving deeper into the code.  I'm on Windows 10, older machine, Intel 4000 display and DirectX12.

Any advice on where to start looking in the code to help debug this?

### LINKED ISSUE #357: cargo run --package tour error (debian)
Hello,

I fail to run examples too:

```
➜  iced git:(master) ✗ RUST_BACKTRACE=1 cargo run --package tour
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/tour`
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] vkEnumeratePhysicalDevices: Failed in dispatch call used to determine number of available GPUs
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader.
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'Request adapter', wgpu/src/window/backend.rs:22:27
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/option.rs:347
  15: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::{{closure}}
             at wgpu/src/window/backend.rs:22
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/future.rs:44
  17: futures_executor::local_pool::block_on::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  18: futures_executor::local_pool::run_executor::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:262
  20: std::thread::local::LocalKey<T>::with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:239
  21: futures_executor::local_pool::run_executor
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  22: futures_executor::local_pool::block_on
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  23: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new
             at wgpu/src/window/backend.rs:21
  24: iced_winit::application::Application::run
             at ./winit/src/application.rs:180
  25: iced::application::Application::run
             at ./src/application.rs:201
  26: iced::sandbox::Sandbox::run
             at ./src/sandbox.rs:139
  27: tour::main
             at examples/tour/src/main.rs:10
  28: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  32: std::panicking::try
             at src/libstd/panicking.rs:281
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  35: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  36: main
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

* Linux PC-Fixe-01 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
* Cedar [Radeon HD 5000/6000/7350/8350 Series]

```
➜  iced git:(master) ✗ sudo find /dev -group video
/dev/fb0
/dev/dri/card0
/dev/dri/renderD128
/dev/dri/controlD64
➜  iced git:(master) ✗ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: X.Org (0x1002)
OpenGL vendor string: X.Org
```

Something can i do ?

### PR DESCRIPTION
**Pull request by hecrj**
This PR implements an OpenGL renderer on top of [`glow`], introduces a [`glutin`] shell, and abstracts a bunch of backend-agnostic rendering logic in a new graphics subcrate.

# `iced_glow`
`iced_glow` is an OpenGL renderer powered by [`glow`] (GL on Whatever). This renderer is meant to be an alternative (not a replacement!) to [`iced_wgpu`] while [`wgpu`] and its ecosystem mature.

As `iced_glow` uses OpenGL, it should offer us better compatibility, stability, and maintainability for the time being. Furthermore, users that currently have OpenGL-based applications should be able to integrate them directly with `iced`.

On a related note, my work on this renderer also prompted me to write and open-source [`glow_glyph`], a direct port of [`wgpu_glyph`] for [`glow`].

Please, feel free to give the renderer a try by switching to the `feature/glow-renderer` branch and running any of the examples! Keep in mind that `Image` and `Svg` widgets are not supported yet.

# `iced_glutin`
`iced_glutin` is a shell on top of [`glutin`]. It can be used to easily initialize OpenGL-based renderers, as it will create and properly configure an OpenGL context for them.

Given that [`glutin`] is built on top of [`winit`] itself, [`iced_winit`] and `iced_glutin` both share a good amount of logic. However, while [`iced_winit`] provides a [`raw-window-handle`] to initialize the chosen renderer, `iced_glutin` provides an OpenGL loader function instead.

The work on this crate also introduced a couple of new concepts in `iced_native` that should ease the integration of `iced` in existing projects (#313). Specifically, a `Program` trait has been added which can be used together with some `program::State` to feed events to a user interface and obtain its drawing primitives. [The `integration` example] has been updated accordingly to showcase how to use them!

# `iced_graphics`
The first draft of `iced_glow` was implemented by copy-pasting a lot of code from [`iced_wgpu`]. As most of this code was backend-agnostic and shared between renderers, it was abstracted away and moved to an intermediate crate: `iced_graphics`.

`iced_graphics` contains a bunch of backend-agnostic types that can be leveraged to build a renderer. The most important concepts it contains are:

- The current [`Primitive`] type from [`iced_wgpu`].
- A [`Layer`] type that flattens a [`Primitive`] tree for rendering.
- A default renderer that can be customized with a generic backend. It implements the `Renderer` trait for all the built-in widgets.
- Other useful types like `Transformation`, `Viewport`, a font loader on top of [`font-kit`], etc.

And I think that's about it! I am aware there is a lot to unpack here. Once I finish writing the documentation for all the changes, I will share a link.

As always, any feedback appreciated and feel free to ask any questions!

[`glow`]: https://github.com/grovesNL/glow
[`glutin`]: https://github.com/rust-windowing/glutin
[`winit`]: https://github.com/rust-windowing/winit
[`glow_glyph`]: https://github.com/hecrj/glow_glyph
[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
[`glyph_brush`]: https://github.com/alexheretic/glyph-brush
[`iced_wgpu`]: https://github.com/hecrj/iced/tree/master/wgpu
[`iced_winit`]: https://github.com/hecrj/iced/tree/master/winit
[`raw-window-handle`]: https://github.com/rust-windowing/raw-window-handle
[`wgpu`]: https://github.com/gfx-rs/wgpu-rs
[OpenGL context]: https://www.khronos.org/opengl/wiki/OpenGL_Context
[The `integration` example]: https://github.com/hecrj/iced/blob/d6bf8955dbca03898e379aae376d91677bb4d223/examples/integration/src/main.rs#L74
[`Primitive`]: https://docs.rs/iced_wgpu/0.2.2/iced_wgpu/enum.Primitive.html
[`Layer`]: https://iced-docs.now.sh/iced_graphics/layer/struct.Layer.html
[`Renderer`]: https://iced-docs.now.sh/iced_graphics/struct.Renderer.html
[`Backend`]: https://iced-docs.now.sh/iced_graphics/backend/trait.Backend.html
[`font-kit`]: https://github.com/servo/font-kit

-----------------

- Fixes #357
- Fixes #350
- Fixes #349
- Fixes #342 
- Fixes #284
- Fixes #257
- Fixes #212
- Fixes #194
- Fixes #182 
- Fixes #148
- Fixes #98
- Fixes #96
- Fixes #72
- Fixes #70

### CODE REVIEW

File: native/src/program.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+/// An interactive, native cross-platform program.
+pub trait Program: Sized {
+    /// The graphics backend to use to draw the [`Program`].
+    ///
+    /// [`Program`]: trait.Program.html
+    type Renderer: Renderer;
+
+    /// The type of __messages__ your [`Program`] will produce.
+    ///
+    /// [`Application`]: trait.Program.html
```
Comment (Songtronix) [inline native/src/program.rs:17]: little copy paste accident I guess:
`Application` -> `Program`

Love your work!

**Comment by hecrj** [comment]
The new documentation is available at https://iced-docs.now.sh/iced/index.html

**Comment by hecrj** [comment]
I think this is ready to be merged!

The OpenGL renderer still does not support the `Image` and `Svg` widgets, but I believe we can tackle that in another PR. There are many foundational changes in this one and it's important we merge it so we can build on top of them.

Given that the OpenGL renderer isn't feature-complete yet, I have kept `iced_wgpu` as the default one. The `iced_glow` renderer can be toggled using the new `glow` feature flag.

**Comment by draivin** [comment]
Currently there is no way to create a glow renderer backend (as it is a `pub(crate)` export), is this intentional until things are more complete?

**Comment by hecrj** [comment]
@draivin Not intentional. I forgot about exposing it 😅

**Comment by hecrj** [comment]
@draivin I have exported it in https://github.com/hecrj/iced/commit/6cb90570a3af18b1a1ad455dc1ce5858f8446aa6.

**Comment by m4b** [comment]
Does this PR indicate that iced will slowly move away from using wgpu (and eventually not at all)?

**Comment by hecrj** [comment]
@m4b 

No, as the description says:

> This renderer is meant to be an alternative (not a replacement!) to iced_wgpu while wgpu and its ecosystem mature.

**Comment by m4b** [comment]
Gosh, sorry I missed that, thanks for clarification :)

**Comment by 0x7CFE** [comment]
Are there any estimates on how hard it is to implement image support for OpenGL renderer? It's the only thing that prevents me from using iced on Raspberry Pi (see #428). With just a couple of shader hacks, everything else works fine.

**Comment by hecrj** [comment]
@0x7CFE It shouldn't be hard to get a similar implementation to the `iced_wgpu` one.

However, we should try to abstract and move [the atlas logic](https://github.com/hecrj/iced/blob/master/wgpu/src/image/atlas.rs) to `iced_graphics` instead of duplicating code. Additionally, it would be great to set the foundations for asynchronous loading of images at the same time.

**Comment by Tarnadas** [comment]
@hecrj is there a tracking issue for `Image` and `Svg` support for the glow feature?

Also, could it be that the current master fails to compile with the glow feature? I'm getting lots of errors.

**Comment by MCOfficer** [comment]
> @hecrj is there a tracking issue for `Image` and `Svg` support for the glow feature?
> 
> Also, could it be that the current master fails to compile with the glow feature? I'm getting lots of errors.

Seconded. I would create an issue myself, but i feel like the OP of a tracking issue should contain all meaningful information, and it would be much better if you had control over that OP.
